services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm
  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/app
    depends_on:
      - db
      - selenium
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: db_history
      DB_PORT: 5432
    tty: true
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: db_history
    ports:
      - "5555:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/setup.sql:/tmp/setup.sql
      - ./db/setup.sh:/docker-entrypoint-initdb.d/setup.sh
volumes:
  db-data:
