definitions:
  data.DetailHistory:
    properties:
      thumbnail_url:
        type: string
      title:
        type: string
      video_id:
        type: string
      watch_date:
        type: string
    type: object
  data.TagNameCount:
    properties:
      count:
        type: integer
      tag_name:
        type: string
    type: object
  data.VideoInfo:
    properties:
      tags:
        items:
          type: string
        type: array
      thumbnail_url:
        type: string
      title:
        type: string
      video_id:
        type: string
    type: object
  data.VideoInfoWithoutTags:
    properties:
      thumbnail_url:
        type: string
      title:
        type: string
      video_id:
        type: string
    type: object
  presentation.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  title: niconico_recap_backend API
  version: "0.1"
paths:
  /history/{date}:
    get:
      description: |-
        dateが指定された場合はその日の5時から29時までのデータを返す
        startDateとendDateが指定された場合はstartDateの5時からからendDateの29時までのデータを返す
        startDateが指定されない場合は1900-01-01, endDateが指定されない場合は現在として扱う
      parameters:
      - description: yyyy-mm-dd
        in: query
        name: date
        type: string
      - description: yyyy-mm-dd
        in: query
        name: startDate
        type: string
      - description: yyyy-mm-dd
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.DetailHistory'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presentation.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presentation.ErrorResponse'
      summary: 指定された日付の視聴履歴を返す
  /summary:
    get:
      description: |-
        指定された期間内に視聴された動画のタグのサマリーを返す
        タグは視聴された回数の降順で返される
        dateが指定された場合はその日の5時から29時までのデータを返す
        startDateとendDateが指定された場合はstartDateの5時からからendDateの29時までのデータを返す
        startDateが指定されない場合は1900-01-01, endDateが指定されない場合は現在として扱う
      parameters:
      - description: yyyy-mm-dd
        in: query
        name: date
        type: string
      - description: yyyy-mm-dd
        in: query
        name: startDate
        type: string
      - description: yyyy-mm-dd
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.TagNameCount'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presentation.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presentation.ErrorResponse'
      summary: 指定された期間内に視聴された動画のタグのサマリーを返す
  /videos:
    get:
      description: |-
        tagが指定された場合はそのタグが含まれる動画を返す
        titleが指定された場合はそのタイトルが含まれる動画を返す
        tagとtitleが指定された場合はtagの条件が優先される
      parameters:
      - description: tag
        in: query
        name: tag
        type: string
      - description: title
        in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.VideoInfoWithoutTags'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presentation.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presentation.ErrorResponse'
      summary: タグやタイトルで動画を検索して返す
  /videos/{videoId}:
    get:
      parameters:
      - description: videoId
        in: path
        name: videoId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.VideoInfo'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presentation.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presentation.ErrorResponse'
      summary: 指定されたvideoIdの動画情報を返す
swagger: "2.0"
